from dydx3.constants import API_HOST_SEPOLIA, API_HOST_MAINNET
from decouple import config

# selected mode

MODE = "DEVELOPMENT"

# Close all open position and orders
ABORT_ALL_POSITIONS = True

# find cointegrated pairs
FIND_COINTEGRATED = True

# MANAGE EXITS
MANAGE_EXITS = True

# place trades
PLACE_TRADES = True

# Resolution
RESOLUTION = "1HOUR"

# Stats window
WINDOW = 21

# Leverage
LEVERAGE = 1

#Tresholds - Opening
MAX_HALF_LIFE = 24
ZSCORE_THRESH = 1.5
USD_PER_TRADE = 100
USD_MIN_COLLATERAL = 1880

#Tresholds - Closing
CLOSE_AT_ZSCORE_CROSS = True

ETHEREUM_ADDRESS = "0x84df9cA98c953de434B6fFF78624d5459eD0dc08"

# KEYS - Production

STARK_PRIVATE_KEY_MAINNET = config("STARK_PRIVATE_KEY_MAINNET")
DYDX_API_KEY_MAINNET = config("DYDX_API_KEY_MAINNET")
DYDX_SECRET_MAINNET = config("DYDX_SECRET_MAINNET")
DYDX_API_PASSPHRASE_MAINNET = config("DYDX_API_PASSPHRASE_MAINNET")

# KEYS - TESTNET
STARK_PRIVATE_KEY_TESTNET = config("STARK_PRIVATE_KEY_TESTNET")
DYDX_API_KEY_TESTNET = config("DYDX_API_KEY_TESTNET")
DYDX_SECRET_TESTNET =  config("DYDX_SECRET_TESTNET")
DYDX_API_PASSPHRASE_TESTNET = config("DYDX_API_PASSPHRASE_TESTNET")

# KEYS - export
STARK_PRIVATE_KEY = STARK_PRIVATE_KEY_MAINNET if MODE == "PRODUCTION" else STARK_PRIVATE_KEY_TESTNET
DYDX_API_KEY = DYDX_API_KEY_MAINNET if MODE == "PRODUCTION" else DYDX_API_KEY_TESTNET
DYDX_SECRET = DYDX_SECRET_MAINNET if MODE == "PRODUCTION" else DYDX_SECRET_TESTNET
DYDX_API_PASSPHRASE = DYDX_API_PASSPHRASE_MAINNET if MODE == "PRODUCTION" else DYDX_API_PASSPHRASE_TESTNET

# HOST - Export
HOST = API_HOST_MAINNET if MODE == "PRODUCTION" else API_HOST_SEPOLIA

# HTTP PROVIDER
HTTP_PROVIDER_TESTNET = "https://eth-sepolia.g.alchemy.com/v2/RgBTjvzKqufZd5WhHrHqslPUjjrWmPhH"
HTTP_PROVIDER_MAINNET = "https://eth-mainnet.g.alchemy.com/v2/wLcBvF75ssUvyKX0_Gvki8E0WIa2-IL8"

HTTP_PROVIDER = HTTP_PROVIDER_MAINNET if MODE == "PRODUCTION" else HTTP_PROVIDER_TESTNET